version: '3'
services:
  pgsql-db:
    image: postgres:13
    restart: always
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - pgsql-data:/var/lib/postgresql/data

  # api:
  #   image: ap-odc_api
  #   ports: 
  #     - 8000:80

volumes:
  pgsql-data:
